### ISSUE TITLE
4 Sound file names do not match the correct sound

### ISSUE THREAD

**Issue by jdwilkin4** [nickytonline/collabiano#10]
**Describe the bug**
When playing with the app, it seems like some of the sound names sound a half step higher then what is listed in the sound file names.

For example, `/assets/sounds/default-theme/c4.mp3` sounds more like a C#4
https://www.musicca.com/piano

It looks like only 4 notes are off. 

Renaming of the files should resolve the issue.
Here is my proposal of the mapping from the current files to new file names that match the correct notes.
https://www.musicca.com/piano

| Current File name      | New File name |
| ----------- | ----------- |
| `/assets/sounds/default-theme/c4.mp3`      | `/assets/sounds/default-theme/c#4.mp3`       |
| `/assets/sounds/default-theme/d4.mp3`      | `/assets/sounds/default-theme/d#4.mp3`       |
| `/assets/sounds/default-theme/f4.mp3`      | `/assets/sounds/default-theme/f#4.mp3`       |
| `/assets/sounds/default-theme/c5.mp3`      | `/assets/sounds/default-theme/c#5.mp3`       |

**To Reproduce**

1. Go to `/assets/sounds/default-theme/c4.mp3`
2. Play the sound
3. Hear a C#4 instead of C4

**Expected behavior**
The following 4 files listed above should be updated to better reflect the correct pitch and note. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nickytonline** [comment]
Thanks for reporting @jdwilkin4! I realized this once i added the octave from freesound.org. I was trying to avoid playing the piano and recording it myself, but I may have to do that but I will try tensing them first like you suggest.

**Comment by nickytonline** [comment]
Fixed by 16eba0f010baa324eae9715060dd5e9b20344403 and 19843e25aadb731650f44a3e562e3ecc5c12ea91.
