### ISSUE TITLE
Feature: Upgrade to eslint-plugin 8.x

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/collabiano#132]
Dependabot has been trying to update to @typescript-eslint/eslint-plugin from 7.0.0 to 8.x for a while now but the builds always fail. I haven't had a chance to look at this.

This would be a great first issue for anyone interested in TypeScript and ESLint.

Here's the latest failure, https://github.com/nickytonline/collabiano/pull/131

**Comment by lmac-1** [comment]
.take 

Can I work on this? :)

**Comment by nickytonline** [comment]
Go for it! Thanks @lmac-1!

**Comment by lmac-1** [comment]
I have a question.. I updated the packages of `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin`. When trying to commit, I get the following errors when `npx lint-staged` is run by the pre-commit hook: 

```

✖ eslint --cache --fix:

/Users/lucymacartney/Documents/Code/open source/collabiano/package-lock.json
  1:1  error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions

/Users/lucymacartney/Documents/Code/open source/collabiano/package.json
  1:1  error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions

✖ 2 problems (2 errors, 0 warnings)

husky - pre-commit script failed (code 1)
```

I don't think that the `no-unused-expressions` rule should be applied to json files. I could extend the `.eslintrc.cjs` `overrides` to ignore this rule for json files: 
```
overrides: [
    {
      files: ['*.json'],
      rules: {
        '@typescript-eslint/no-unused-expressions': 'off',
      },
    },
  ],
```

or have eslint ignore package.json and package-lock.json completely. 

Which would you prefer, or is there another way you'd like me to fix this? Thanks!

**Comment by nickytonline** [comment]
I think eslint can probably ignore package.json and package-lock.json. I honestly didn't think eslint checked those files by default.

**Comment by nickytonline** [comment]
No pressure to @lmac-1, but once you sort this out, it's probably the same issue in https://github.com/nickytonline/astro-partykit-starter/pull/231 which is the template site I created to create collabiano.

**Comment by lmac-1** [comment]
Cool, thanks! And sure, I can look into the other project too :)
