### ISSUE TITLE
Note mismatch between piano illustration and sounds

### ISSUE THREAD

**Issue by jdwilkin4** [nickytonline/collabiano#9]
**Describe the bug**
When I was trying out the app, I clicked on the first note which is depicted as an F but the sound and note named displayed said it was a C. Here are all of the current notes displayed when only clicking on the white keys

<img width="559" alt="Screenshot 2024-01-01 at 10 43 00 PM" src="https://github.com/nickytonline/collabiano/assets/67210629/042239c1-a4bf-48ee-9fec-b7e9d9749380">

It looks like everything would need to be shifted by a 4th so the first sound would be an F4 so it matches the piano illustration.

<img width="520" alt="Screenshot 2024-01-01 at 10 46 45 PM" src="https://github.com/nickytonline/collabiano/assets/67210629/c1616635-1818-4938-80d6-8649477a1762">

**To Reproduce**

1. Go to https://pianoparty.netlify.app/
2. Click on the first white key
3. See the result say C4
4. Compare that first note to F4 from this online virtual piano to hear the difference https://www.musicca.com/piano

**Expected behavior**
Notes should match with illustration

**Screenshots**
see screenshots above

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nickytonline** [comment]
Fixed by 16eba0f010baa324eae9715060dd5e9b20344403 and 19843e25aadb731650f44a3e562e3ecc5c12ea91.
